export class Service {
  id: number;
  name: string;
  duration: string;
  price: string;
  description: string;
}

export const SERV: Service[] = [
  {id:1,name:'Strzyżenie męskie',duration:'15 - 30 min',price:'25 PLN',description:'Podstawowy pakiet usług dla Panów. Fryzjer rozpoczyna od mycia włosów szamponem pielęgnacyjnym i wykonuje relaksujący masaż skóry głowy. Następnie nakłada na włosy odżywkę. Kolejny etap to to precyzyjne strzyżenie męskie za pomocą nożyczek i/lub maszynki. Usługę kończy modelowanie włosów zgodne z życzeniem Klienta'},
  {id:2,name:'Strzyżenie damskie',duration:'45 - 60 min',price:'100 PLN',description:'Podstawowy pakiet usług dla Pań. Fryzjer rozpoczyna od mycia włosów szamponem pielęgnacyjnym i wykonuje relaksujący masaż skóry głowy. Następnie nakłada na włosy odżywkę. Kolejny etap to precyzyjne strzyżenie damskie za pomocą nożyczek i/lub maszynk. Końcówka usługi to modelowanie włosów zgodne z życzeniem Klientki.'},
  {id:3,name:'Farbowanie włosów',duration:'60 - 90 min',price:'60 PLN',description:'Farbowanie włosów jest jednym z najpopularniejszych usług wykonywanych w salonach fryzjerskich Lovely Look. Kolor włosów dobrze dobrany do naszej osobowości może dodać nam pewności siebie i energii. Niezależnie do tego, czy jest to kolor pełny, wyrazisty czy delikatny i subtelny, daje on „nowe życie” włosom, wydobywa zalety twarzy lub tuszuje cechy przez nas nielubiane. Koloryzacja włosów wykonywana jest przez nas profesjonalnymi farbami Indola.'},
  {id:4,name:'Klasyczne koloryzacja włosów',duration:'45 - 90 min',price:'50 PLN',description:'To farbowanie włosów na jeden wybrany kolor. Pozwala na całkowitą zmianę imagu i pomaga ukryć siwe włosy. Decydując się na nowy kolor, musisz zwrócić uwagę, na to żeby barwa włosów harmonizowała z odcieniem karnacji i oprawy oczu. Większość Polek należy do typu zimy lub lata – czyli mają zimny typ urody i powinny wybierać kolory włosów o chłodnym odcieniu. Poproś fryzjera o pomoc w wyborze odpowiedniego koloru.  Nie kieruj się tym co zobaczysz na zdjęciu w prasie lub u swojej koleżanki, łatwo w taki sposób dokonać złego wyboru. Pamiętaj, że jeśli marzysz o kolorze jaśniejszym niż Twój naturalny, konieczne będzie rozjaśnienie włosów przed nałożeniem wybranej farby. Do ceny usługi trzeba doliczyć koszt strzyżenia lub modelowania.'},
  {id:5,name:'Balayage',duration:'45 - 60 min',price:'100 PLN',description:'To gra kolorów i światła, pozwala na subtelne podkreślenie i rozjaśnienie koloru włosów. Wyrazistość pasemek i ilość zastosowanych kolorów jest uzależniona od indywidualnego gustu – fryzjer dobierze odpowiednią kolorystykę. Przy zastosowaniu tej przyjaznej techniki, odrost nie jest wyraźnie widoczny, sprawdza się więc ona świetnie jeśli chcemy zniwelować siwe włosy. Do ceny usługi trzeba doliczyć koszt strzyżenia lub modelowania.'},
  {id:6,name:'Dekoloryzacja włosów',duration:'90 - 120 min',price:'120 PLN',description:'Jest to usługa wykonywana w przypadku radykalnej zmiany koloru. Fryzjer zależnie od stanu włosów wybiera odpowiedni produkt do dekoloryzacji. Produkt do dekoloryzacji pozostaje na włosach przez czas określony przez fryzjera w zależności od pożądanego efektu, po czym zostaje spłukany. Włosy zostają dokładnie umyte szamponem pielęgnacyjnym. Po tej usłudze konieczne jest nałożenie wybranej farby'},
  {id:7,name:'Strzyżenie grzywki',duration:'10 - 20 min',price:'45 PLN',description:'Podcięcie grzywki za pomocą nożyczek lub maszynki, bez mycia włosów i modelowania.'},
  {id:8,name:'Modelowanie włosów',duration:'30 - 60 min',price:'50 PLN',description:'Umycie włosów szamponem pielęgnacyjnym, nałożenie odżywki a następnie wymodelowanie ich za pomocą szczotek i suszarki, przy użyciu produktów do stylizacji'},
  {id:9,name:'Pielęgnacja włosów',duration:'60 - 90 min',price:'50 PLN',description:'Modelowanie, prostowanie, farbowanie i rozjaśnianie – włosy są narażone na wiele negatywnych czynników. W efekcie są przesuszone, trudne do ułożenia, matowe. Jak temu zaradzić? Najlepsze rozwiązanie to właściwa pielęgnacja.'},
  {id:10,name:'Przedłużanie włosów',duration:'60 - 90 min',price:'250 PLN',description:'Przedłużenie włosów do maksymalnej długości 40 cm, od  60 do 120 pasm. Pasemka, których używamy są w 100% naturalnymi włosami, renomowanej włoskiej marki Giambertone. Łączymy je w pobliżu nasady z Twoimi włosami za pomocą około 5 milimetrowego łącznika. Ten mały konektor jest bardzo cienki i płaski, wykonany ze stopu metali nierdzewnych, hypoalergiczny i całkowicie niewidoczny.'},
  {id:11,name:'Zagęszczanie włosów',duration:'20 - 45 min',price:'250 PLN',description:'Dodanie włosom objętości za pomocą doczepionych pasm, od 15 do 60 pasm. Pasemka, których używamy są w 100% naturalnymi włosami, renomowanej włoskiej marki Giambertone. Łączymy je w pobliżu nasady z Twoimi włosami za pomocą około 5 milimetrowego łącznika. Ten mały konektor jest bardzo cienki i płaski, wykonany ze stopu metali nierdzewnych, hypoalergiczny i całkowicie niewidoczny.'},
  {id:12,name:'Doczepianie włosów',duration:'15 - 60 min',price:'100 PLN',description:'Podkreślenie wybranego fragmentu fryzury np. grzywki, lub dołożenie kilku pasm  w wybranych kolorze aby uzyskać efekt pasemek – do  15 pasm. Pasemka, których używamy są w 100% naturalnymi włosami, renomowanej włoskiej marki Giambertone. Łączymy je w pobliżu nasady z Twoimi włosami za pomocą około 5 milimetrowego łącznika. Ten mały konektor jest bardzo cienki i płaski, wykonany ze stopu metali nierdzewnych, hypoalergiczny i całkowicie niewidoczny.'}

];
